variables:
  projectName: WebGoat.Net
  projectPath: library/tartarus
  dockerRepository: $(projectPath)/$(projectName)
  imageName: $(dockerRegistry)/$(dockerRepository)
  imageTag: '$(Build.BuildId)'

trigger:
- master
pr:
- master

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: 'Kube'
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Building Image
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        containerRegistry: 'Harbor'
        repository: $(dockerRepository)
        command: 'buildandpush'
        Dockerfile: '**/dockerfile'
        tags: | 
          $(imageTag)
          latest
