# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Kube' 
  vmImage: 'ubuntu-latest'

- task: Docker@2
  inputs:
    containerRegistry: 'Harbor'
    repository: '/library/tartarus/webgoat.net'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
